### ISSUE TITLE
 No Compatible Fields: The "flight-track-*" index pattern does not contain any of the following field types: geo_point

### ISSUE THREAD

**Issue by ipl2004** [kosho/flight-track#5]
"template": "flight-track-*",
    "settings": {
      "number_of_shards": 1,
      "number_of_replicas" : 0
      "index.refresh_interval": "5s"

![screenshot from 2017-04-06 13-26-21](https://cloud.githubusercontent.com/assets/10930322/24769604/b2be5924-1acc-11e7-8854-d93f9f7c9b17.png)

**Comment by kosho** [comment]
Hi @ipl2004. It's not an issue related to my repo. My index pattern template contains proper `geo_point` type for the `location` field. You can just refresh the index pattern of Kibana and see what happens.
